// friendCodes.js — anonymous accountability pairing service.
//
// Two users pair via a 6-character code. The inviter generates a code,
// shares it out-of-band, the partner enters it in the app. Once paired,
// each side sees the OTHER's currentStreak + anonUsername (and only those
// two fields — no chat, no feed, no comments).
//
// The service is a thin client wrapper over the Supabase tables defined in
// migrations/001_friend_pairs.sql:
//   • friend_codes — pending invitations (24h TTL)
//   • friend_pairs — confirmed pairings (1:1, unique per user)
//   • public_streaks view — partner's live streak data (read-only)
//   • redeem_friend_code() RPC — atomic lookup + pair creation
//
// All functions are guarded against the SUPABASE_CONFIGURED flag so a
// dev build without credentials degrades gracefully.

import { supabase, SUPABASE_CONFIGURED } from './supabase';

// Code alphabet — 6 chars from a 32-char set that excludes the visually
// ambiguous pairs (0/O, 1/I/L). Yields ~10^9 codes, more than enough for
// any plausible user count given the 24h TTL.
const CODE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
const CODE_LENGTH = 6;

/**
 * Generate a random 6-character code from the unambiguous alphabet.
 */
function generateRandomCode() {
  let out = '';
  for (let i = 0; i < CODE_LENGTH; i++) {
    out += CODE_ALPHABET.charAt(
      Math.floor(Math.random() * CODE_ALPHABET.length),
    );
  }
  return out;
}

/**
 * Normalize a user-typed code: strip whitespace, uppercase. The server
 * uppercases too, so this is just a UX nicety for displaying back to the
 * user what they actually entered.
 */
export function normalizeFriendCode(input) {
  return String(input || '').toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, CODE_LENGTH);
}

/**
 * Create a new pending code for the current user. If the user already has
 * a code outstanding we delete it first so there's never more than one
 * active code per user (otherwise the UI would have to pick which one to
 * show). Returns the code string on success, null on failure.
 *
 * Race-condition tolerant: if the random code happens to collide with an
 * existing code (extremely unlikely given the alphabet size + TTL), we
 * retry up to 3 times before giving up.
 */
export async function generateFriendCode() {
  if (!SUPABASE_CONFIGURED) return null;
  try {
    const { data: { user } = {} } = await supabase.auth.getUser();
    if (!user?.id) return null;

    // Burn any existing pending code for this user — single-outstanding-code
    // model keeps the UI simple.
    await supabase.from('friend_codes').delete().eq('user_id', user.id);

    for (let attempt = 0; attempt < 3; attempt++) {
      const code = generateRandomCode();
      const { error } = await supabase
        .from('friend_codes')
        .insert({ code, user_id: user.id });
      if (!error) return code;
      // Primary-key collision = code already exists. Retry with a new one.
      // Anything else is a real error and we bail.
      if (error.code !== '23505') {
        console.warn('[friendCodes] generate insert error:', error.message);
        return null;
      }
    }
    console.warn('[friendCodes] generate: too many collisions, giving up');
    return null;
  } catch (e) {
    console.warn('[friendCodes] generate exception:', e?.message);
    return null;
  }
}

/**
 * Redeem a code generated by another user. Calls the SECURITY DEFINER RPC
 * which atomically validates + creates the pair. Returns
 *   { partnerId, partnerName, partnerStreak }  on success
 *   { error: 'reason' }                         on failure (so the UI can
 *                                              show a precise message)
 */
export async function redeemFriendCode(code) {
  if (!SUPABASE_CONFIGURED) return { error: 'not_configured' };
  const normalized = normalizeFriendCode(code);
  if (normalized.length !== CODE_LENGTH) {
    return { error: 'invalid_length' };
  }
  try {
    const { data, error } = await supabase.rpc('redeem_friend_code', {
      code_input: normalized,
    });
    if (error) {
      console.warn('[friendCodes] redeem error:', error.message);
      // Map common Postgres exception codes to UI-friendly reasons so the
      // copy can be specific ("you can't pair with yourself" vs. "already
      // paired" vs. generic).
      const msg = (error.message || '').toLowerCase();
      if (msg.includes('cannot pair with yourself')) return { error: 'self_pair' };
      if (msg.includes('already paired')) return { error: 'already_paired' };
      if (msg.includes('code not found') || msg.includes('expired')) {
        return { error: 'not_found' };
      }
      if (msg.includes('not authenticated')) return { error: 'not_authenticated' };
      return { error: 'unknown' };
    }
    // RPC returns a single-row table set; supabase.rpc returns the array.
    const row = Array.isArray(data) ? data[0] : data;
    if (!row?.partner_id) return { error: 'unknown' };
    return {
      partnerId: row.partner_id,
      partnerName: row.partner_name,
      partnerStreak: row.partner_streak || 0,
    };
  } catch (e) {
    console.warn('[friendCodes] redeem exception:', e?.message);
    return { error: 'unknown' };
  }
}

/**
 * Look up the current user's pair (if any). Returns
 *   { partnerId, partnerName, partnerStreak, lastCompletedDate, pairedAt }
 *   or null if not paired.
 *
 * Resolves the partner's id by checking which side of the pair row the
 * caller is on, then joins to public_streaks for the live streak/name data.
 */
export async function getFriendPair() {
  if (!SUPABASE_CONFIGURED) return null;
  try {
    const { data: { user } = {} } = await supabase.auth.getUser();
    if (!user?.id) return null;

    const { data: pair, error: pairErr } = await supabase
      .from('friend_pairs')
      .select('id, user_a, user_b, paired_at')
      .or(`user_a.eq.${user.id},user_b.eq.${user.id}`)
      .maybeSingle();
    if (pairErr) {
      console.warn('[friendCodes] getFriendPair pair error:', pairErr.message);
      return null;
    }
    if (!pair) return null;

    const partnerId = pair.user_a === user.id ? pair.user_b : pair.user_a;
    const stats = await fetchPartnerStats(partnerId);
    return {
      partnerId,
      partnerName: stats?.anonUsername || 'monk',
      partnerStreak: stats?.currentStreak || 0,
      lastCompletedDate: stats?.lastCompletedDate || null,
      pairedAt: pair.paired_at,
    };
  } catch (e) {
    console.warn('[friendCodes] getFriendPair exception:', e?.message);
    return null;
  }
}

/**
 * Break the pair for the current user. Either side can unpair unilaterally —
 * stoic discipline app, no consent dance. The RLS policy on the table
 * already restricts delete to participants.
 */
export async function unpair() {
  if (!SUPABASE_CONFIGURED) return false;
  try {
    const { data: { user } = {} } = await supabase.auth.getUser();
    if (!user?.id) return false;
    const { error } = await supabase
      .from('friend_pairs')
      .delete()
      .or(`user_a.eq.${user.id},user_b.eq.${user.id}`);
    if (error) {
      console.warn('[friendCodes] unpair error:', error.message);
      return false;
    }
    return true;
  } catch (e) {
    console.warn('[friendCodes] unpair exception:', e?.message);
    return false;
  }
}

/**
 * Fetch the partner's live streak data from the public_streaks view.
 * Returns null if the partner has no user_state row yet (e.g., brand-new
 * account that hasn't done a lesson).
 */
export async function fetchPartnerStats(partnerId) {
  if (!SUPABASE_CONFIGURED || !partnerId) return null;
  try {
    const { data, error } = await supabase
      .from('public_streaks')
      .select('user_id, current_streak, longest_streak, last_completed_date, anon_username')
      .eq('user_id', partnerId)
      .maybeSingle();
    if (error) {
      console.warn('[friendCodes] fetchPartnerStats error:', error.message);
      return null;
    }
    if (!data) return null;
    return {
      userId: data.user_id,
      currentStreak: data.current_streak || 0,
      longestStreak: data.longest_streak || 0,
      lastCompletedDate: data.last_completed_date || null,
      anonUsername: data.anon_username || null,
    };
  } catch (e) {
    console.warn('[friendCodes] fetchPartnerStats exception:', e?.message);
    return null;
  }
}

/**
 * Get the user's current outstanding code (the one they generated but
 * nobody has redeemed yet). Returns { code, expiresAt } or null. Useful
 * for restoring the "show me my code" view after app restart.
 */
export async function getMyPendingCode() {
  if (!SUPABASE_CONFIGURED) return null;
  try {
    const { data: { user } = {} } = await supabase.auth.getUser();
    if (!user?.id) return null;
    const { data, error } = await supabase
      .from('friend_codes')
      .select('code, expires_at')
      .eq('user_id', user.id)
      .gt('expires_at', new Date().toISOString())
      .maybeSingle();
    if (error) {
      console.warn('[friendCodes] getMyPendingCode error:', error.message);
      return null;
    }
    if (!data) return null;
    return { code: data.code, expiresAt: data.expires_at };
  } catch (e) {
    console.warn('[friendCodes] getMyPendingCode exception:', e?.message);
    return null;
  }
}
