-- ──────────────────────────────────────────────────────────────────────────────
-- Friend Codes — anonymous accountability pairing
-- ──────────────────────────────────────────────────────────────────────────────
-- Two users pair via a 6-digit code. Once paired, each sees the OTHER's
-- currentStreak + anonUsername. When one breaks their streak, the other gets
-- a push notification. No chat, no feed, no comments — just visibility of one
-- accountability partner's streak. The unique constraints enforce a 1:1 pair:
-- each user can be in at most one pair at a time.
--
-- Codes are pending invitations. A code lives in friend_codes until a second
-- user redeems it via the SECURITY DEFINER redeem_friend_code() RPC, at which
-- point the code is deleted and a friend_pairs row is created. Codes expire
-- after 24h to avoid stale codes floating around forever.
--
-- The redemption RPC runs SECURITY DEFINER because the redeeming user cannot
-- read friend_codes rows belonging to the inviter under RLS — but we still
-- need to look the code up and consume it atomically. The function itself
-- validates the caller is authenticated and not pairing with themselves.
-- ──────────────────────────────────────────────────────────────────────────────

-- ── Table: friend_pairs ─────────────────────────────────────────────────────
create table if not exists public.friend_pairs (
  id          uuid primary key default gen_random_uuid(),
  user_a      uuid references auth.users(id) on delete cascade not null,
  user_b      uuid references auth.users(id) on delete cascade not null,
  paired_at   timestamptz default now() not null,
  -- Single pairing per user (1:1 monogamous pair model)
  constraint friend_pairs_unique_a unique (user_a),
  constraint friend_pairs_unique_b unique (user_b),
  constraint friend_pairs_no_self_pair check (user_a <> user_b)
);

create index if not exists friend_pairs_user_b_idx
  on public.friend_pairs (user_b);

-- ── Table: friend_codes ─────────────────────────────────────────────────────
-- Pending codes generated by a user waiting for a partner to redeem.
create table if not exists public.friend_codes (
  code        text primary key check (length(code) = 6),
  user_id     uuid references auth.users(id) on delete cascade not null,
  created_at  timestamptz default now() not null,
  expires_at  timestamptz default (now() + interval '24 hours') not null
);

create index if not exists friend_codes_user_id_idx
  on public.friend_codes (user_id);

-- ── RLS: friend_pairs ───────────────────────────────────────────────────────
alter table public.friend_pairs enable row level security;

drop policy if exists "friend_pairs: users see their own pair" on public.friend_pairs;
create policy "friend_pairs: users see their own pair"
  on public.friend_pairs for select
  using (auth.uid() = user_a or auth.uid() = user_b);

drop policy if exists "friend_pairs: users create their own pair" on public.friend_pairs;
create policy "friend_pairs: users create their own pair"
  on public.friend_pairs for insert
  with check (auth.uid() = user_a or auth.uid() = user_b);

drop policy if exists "friend_pairs: users delete their own pair" on public.friend_pairs;
create policy "friend_pairs: users delete their own pair"
  on public.friend_pairs for delete
  using (auth.uid() = user_a or auth.uid() = user_b);

-- ── RLS: friend_codes ───────────────────────────────────────────────────────
alter table public.friend_codes enable row level security;

drop policy if exists "friend_codes: users see codes they created" on public.friend_codes;
create policy "friend_codes: users see codes they created"
  on public.friend_codes for select
  using (auth.uid() = user_id);

drop policy if exists "friend_codes: users create their own codes" on public.friend_codes;
create policy "friend_codes: users create their own codes"
  on public.friend_codes for insert
  with check (auth.uid() = user_id);

drop policy if exists "friend_codes: users delete their own codes" on public.friend_codes;
create policy "friend_codes: users delete their own codes"
  on public.friend_codes for delete
  using (auth.uid() = user_id);

-- IMPORTANT: redemption needs ANY authenticated user to look up a code by
-- exact match, then create a pair. The standard RLS policy above only lets
-- the code owner SELECT — so the redeemer can't see the code. We use a
-- SECURITY DEFINER function (below) to bypass this constraint safely, with
-- explicit checks inside the function for: (1) caller is authenticated,
-- (2) caller is not the code owner, (3) code is not expired, (4) neither
-- user is already paired.

-- ── View: public_streaks ────────────────────────────────────────────────────
-- Exposes user_id + currentStreak + lastCompletedDate + anonUsername to
-- authenticated users. Source is the user_state.payload jsonb column (where
-- AppContext.cloudSync writes the streak fields). We re-use that single
-- source of truth instead of duplicating into a dedicated table so partner
-- streaks stay live as soon as the partner pushes state to cloud.
--
-- Read access is gated to authenticated only (no anon role) so the streak
-- data isn't browseable from outside the app. RLS on the underlying
-- user_state table doesn't apply to a view by default unless we mark it
-- SECURITY INVOKER (Postgres 15+); we instead grant SELECT explicitly and
-- accept that any authenticated user can read any other user's anonUsername
-- + streak. That's the same exposure level the streak_leaderboard table
-- already provides, so this view doesn't widen the privacy surface.
create or replace view public.public_streaks as
select
  user_id,
  coalesce((payload->>'currentStreak')::int, 0)   as current_streak,
  coalesce((payload->>'longestStreak')::int, 0)   as longest_streak,
  payload->>'lastCompletedDate'                   as last_completed_date,
  payload->>'anonUsername'                        as anon_username
from public.user_state;

grant select on public.public_streaks to authenticated;

-- ── Function: redeem_friend_code ────────────────────────────────────────────
-- SECURITY DEFINER so the function can read ANY row of friend_codes (RLS
-- on friend_codes only lets the owner select). The function still enforces:
--   • caller must be authenticated (auth.uid() not null)
--   • code must exist
--   • code must not be expired
--   • code creator must not be the caller (no self-pair)
--   • neither user may already be in a pair
--
-- Returns the partner's anonUsername + user_id + currentStreak (so the
-- client can populate the friendPair state immediately without a follow-up
-- query). Throws on validation failure so the client error toast is precise.
create or replace function public.redeem_friend_code(code_input text)
returns table (
  partner_id     uuid,
  partner_name   text,
  partner_streak int
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caller        uuid;
  v_inviter       uuid;
  v_inviter_name  text;
  v_inviter_streak int;
begin
  v_caller := auth.uid();
  if v_caller is null then
    raise exception 'not authenticated' using errcode = '42501';
  end if;

  -- Normalize for lookup — codes are stored UPPERCASE (client also uppercases)
  -- so users typing in mixed case still hit a match.
  code_input := upper(trim(code_input));
  if length(code_input) <> 6 then
    raise exception 'invalid code length' using errcode = '22023';
  end if;

  -- Lookup + expiry check in one atomic select
  select user_id into v_inviter
  from public.friend_codes
  where code = code_input
    and expires_at > now();

  if v_inviter is null then
    raise exception 'code not found or expired' using errcode = 'P0002';
  end if;

  if v_inviter = v_caller then
    raise exception 'cannot pair with yourself' using errcode = '22023';
  end if;

  -- Neither party may already be in a pair. We check both directions because
  -- a user could be either user_a or user_b.
  if exists (
    select 1 from public.friend_pairs
    where user_a = v_caller or user_b = v_caller
       or user_a = v_inviter or user_b = v_inviter
  ) then
    raise exception 'already paired' using errcode = '23505';
  end if;

  -- Create the pair (inviter = user_a by convention)
  insert into public.friend_pairs (user_a, user_b)
  values (v_inviter, v_caller);

  -- Burn the code so it can't be re-used
  delete from public.friend_codes where code = code_input;

  -- Pull inviter's anonUsername + currentStreak so the client can render
  -- the paired state immediately. Falls back gracefully if the inviter's
  -- user_state row hasn't been created yet (new account, no lessons done).
  select
    coalesce(payload->>'anonUsername', 'monk'),
    coalesce((payload->>'currentStreak')::int, 0)
  into v_inviter_name, v_inviter_streak
  from public.user_state
  where user_id = v_inviter;

  return query select
    v_inviter as partner_id,
    coalesce(v_inviter_name, 'monk') as partner_name,
    coalesce(v_inviter_streak, 0) as partner_streak;
end;
$$;

-- Allow authenticated users to call the function (SECURITY DEFINER takes care
-- of the elevated permissions internally).
grant execute on function public.redeem_friend_code(text) to authenticated;
